services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    command: --local-infile=1 --default-authentication-plugin=mysql_native_password --secure-file-priv=/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_NAME:-railway}
      MYSQL_USER: ${DB_USER:-railway}
      MYSQL_PASSWORD: ${DB_PASSWORD:-change-me}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-change-root-password}
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d

  www:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/html/
    environment:
      DB_NAME: ${DB_NAME:-railway}
      DB_HOST: db
      DB_USER: ${DB_USER:-railway}
      DB_PASSWORD: ${DB_PASSWORD:-change-me}
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
